print('UCHBURCHAK')
print('     *')
print('    ***')
print('   *****')
print('  *******')
print(' *********')
print('***********')
print("to'rtburchak")
print("********")
print("*      *")
print("*      *")
print("********")
print('+, -')
print('7+8=',7+8)
print('15-7=',15-7)
print('aylana')
print('     ****')
print('  *  	  *')
print('*   	        *')
print('*   	        *')
print('*   	        *')
print('  *   	  *')
print('   	****')
print('doira')
print('     ****')
print('  **********')
print('**************')
print('**************')
print('**************')
print('  ***********')
print('   	****')
print('archa')
print('     *')
print('    ***')
print('   *****')
print('  *******')
print(' *********')
print('***********')
print('    ***')
print('    ***')
print('gipatenuzali uchburchak')
print('                 *')
print('              *  *')
print('           *     *')
print('        *        *')
print('     *           *')
print('  *              *')
print('******************')